language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-meanp' ]; then cd .. && eval "mv $currentfolder generator-meanp" && cd generator-meanp; fi

